### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by khuonghoanghuy** [Vortex2Oblivion/hxpy#8]
how can i made them like using pygame?

**Comment by Vortex2Oblivion** [comment]
Can you elaborate

**Comment by khuonghoanghuy** [comment]
like hmmm using script? import global variable and stuff?

**Comment by Vortex2Oblivion** [comment]
> like hmmm using script? import global variable and stuff?

You can't really do that with this since i never got it working

**Comment by khuonghoanghuy** [comment]
then i close this issues tho
